### ISSUE TITLE
Memory complexity

### ISSUE THREAD

**Issue by fredcallaway** [wmayner/pyemd#1]
Thanks for creating this wrapper! I'm trying to use it for an fMRI meta-analysis, but am running into memory overload problems. Do you by chance know the approximate memory complexity of this algorithm?

**Comment by wmayner** [comment]
Glad you're finding it useful! I'm afraid I don't know the memory complexity—but there may be information on that on the [website for the algorithm](http://www.ariel.ac.il/sites/ofirpele//FastEMD/code/) or in the [relevant paper](http://www.ariel.ac.il/sites/ofirpele//publications/ICCV2009.pdf). You could also try to get in touch with the authors.
