### ISSUE TITLE
something about weights and different signatures size

### ISSUE THREAD

**Issue by gsp2014** [wmayner/pyemd#11]
if I want to add weights and the signature size is different, what can I do?

**Comment by wmayner** [comment]
You could pad the smaller signature with zeros and then enforce that no mass is moved to those bins by making the corresponding entries in the distance matrix appropriately large.

I'm not sure what you mean by weights; do you mean that some mass should count more than other mass? I don't think that can be done in general, but it may be worth thinking about whether you could achieve what you want by either simply adding more mass to the higher-weighted bins or encoding the weights in the distance matrix somehow.
