### ISSUE TITLE
 pip  install  error about  gcc

### ISSUE THREAD

**Issue by wuxiaobo** [wmayner/pyemd#18]
pip install pyemd
Collecting pyemd
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requebject at 0xf62b55cc>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pyemd/
  Using cached pyemd-0.4.3.tar.gz
Requirement already satisfied: numpy<2.0.0,>=1.9.0 in ./anaconda3/lib/python3.6/site-packages (from pyemd)
Building wheels for collected packages: pyemd
  Running setup.py bdist_wheel for pyemd ... error
  Complete output from command /home/XXXXX/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4hgf2w8e__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp0g4l273wpip-wheel- --
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/pyemd
  copying pyemd/__about__.py -> build/lib.linux-x86_64-3.6/pyemd
  copying pyemd/__init__.py -> build/lib.linux-x86_64-3.6/pyemd
  running build_ext
  building 'pyemd.emd' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/pyemd
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wuxiaobo/anaconda3/include/python3.6m -Iy/core/include -c pyemd/emd.cpp -o build/temp.linux-x86_64-3.6/pyemd/emd.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from /home/XXXXX/anaconda3/include/python3.6m/Python.h:50:0,
                   from pyemd/emd.cpp:16:
  /home/XXXXX/anaconda3/include/python3.6m/pyport.h:686:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/g
   #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
    ^
  In file included from /home/XXXXX/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                   from /home/XXXXX/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /home/XXXXX/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from pyemd/emd.cpp:467:
  /home/XXXXX/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Usin_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyemd
  Running setup.py clean for pyemd
Failed to build pyemd
Installing collected packages: pyemd
  Running setup.py install for pyemd ... error
    Complete output from command /home/XXXX/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4hgf2ile__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u3zpb6rz-record/compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/pyemd
    copying pyemd/__about__.py -> build/lib.linux-x86_64-3.6/pyemd
    copying pyemd/__init__.py -> build/lib.linux-x86_64-3.6/pyemd
    running build_ext
    building 'pyemd.emd' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/pyemd
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/XXXXX/anaconda3/include/python3.6m mpy/core/include -c pyemd/emd.cpp -o build/temp.linux-x86_64-3.6/pyemd/emd.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from /home/XXXXX/anaconda3/include/python3.6m/Python.h:50:0,
                     from pyemd/emd.cpp:16:
    /home/XXXXX/anaconda3/include/python3.6m/pyport.h:686:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc
     #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
      ^
    In file included from /home/XXXXX/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                     from /home/XXXXX/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/XXXXX/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pyemd/emd.cpp:467:
    /home/XXXXX/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "UsNO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    error: command 'gcc' failed with exit status 1

**Comment by wmayner** [comment]
I can't guarantee that PyEMD will work with Anaconda. Try installing it into a fresh Python 3 virtualenv and see if the problem persists.
