### ISSUE TITLE
What is the distance matrix?

### ISSUE THREAD

**Issue by fsfeng** [wmayner/pyemd#19]
Hi, not necessarily an issue, what precisely is the distance matrix required? Thanks.

**Comment by wmayner** [comment]
The `distance_matrix` parameter encodes the metric that underlies the [Earth Mover's Distance](https://en.wikipedia.org/wiki/Earth_mover%27s_distance). The EMD between two distributions is the minimal cost of transforming one distribution of “earth” into the other, where _cost_ means `(amount of “earth”) * (distance it needs to be transported)`. The second term in that product is given by the underlying metric.

So, the distance matrix can be whatever you want as long as it encodes a [metric](https://en.wikipedia.org/wiki/Metric_(mathematics)) (it must be symmetric and satisfy the triangle inequality). Note that the software will not warn you if this is not true.
