### ISSUE TITLE
ValueError: Signature dimension cannot be larger than dimensions of distance matrix

### ISSUE THREAD

**Issue by happenzZ** [wmayner/pyemd#20]
Hi, 

I get an error shown as follow:

pyemd/emd.pyx in pyemd.emd.emd (pyemd/emd.cpp:2045)()

pyemd/emd.pyx in pyemd.emd.validate (pyemd/emd.cpp:1769)()

**ValueError: Signature dimension cannot be larger than dimensions of distance matrix**

the dimension of my variables are shown here:
first_signature.shape = (363, 363)
second_signature.shape = (363,)
distance_matrix.shape =  (363,)

**What does the error means?**

**Comment by wmayner** [comment]
It looks like you have the arguments mixed up. The distance matrix should be `N x N`, while each signature should be length `N`. So, you've named the first signature `second_signature`, the second signature `distance_matrix`, and the distance matrix `first_signature`.
