### ISSUE TITLE
'error: Microsoft Visual C++ 14.0 is required' when run pip install

### ISSUE THREAD

**Issue by nazmibojan** [wmayner/pyemd#30]
Hi All,

Sorry for this newbie question. I got this error after run `pip install pyemd`:
`building 'pyemd.emd' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools`

I think I have installed VCC 14.0. This is my program screenshots:
![vcc](https://user-images.githubusercontent.com/17125575/39691514-f99ed224-5207-11e8-9826-55af6955c072.JPG)

How can I solve this problem?
Thank you very much.

Regards,
Nazmi

**Comment by wmayner** [comment]
Hi Nazmi,

I'm not very familiar with using Python on Windows, and I can only support PyEMD on Linux and macOS systems. However, I can recommend that you try using [Anaconda's distribution of Python](https://conda.io/docs/user-guide/install/download.html): there is a [conda-forge build of PyEMD available](https://anaconda.org/conda-forge/pyemd). I've found that this is often the best way for Windows users to run Python packages.

Cheers,
Will

**Comment by kdalbey** [comment]
[https://www.scivision.dev/python-windows-visual-c-14-required/](url) should provide a solution to this problem
