### ISSUE TITLE
Can distance_matrix be sparse matrix?

### ISSUE THREAD

**Issue by manishbansal-fk** [wmayner/pyemd#31]

**Comment by wmayner** [comment]
No, because the distance matrix is passed to the C++ library that does the optimization. This library doesn't support dealing with sparse matrices. You're welcome to submit a PR if this is an important feature for you, but it will be a lot of work.

**Comment by manishbansal-fk** [comment]
Thanks for update !!

Just curious which C++ lib pyemd uses ?

**Comment by wmayner** [comment]
See the first sentence of the README. The code is in `pyemd/lib`.
