### ISSUE TITLE
Some question about the speed

### ISSUE THREAD

**Issue by cenaliu** [wmayner/pyemd#34]
Hi, wmayner, thanks for your wonderful code! The speed of this python wrapper is very fast. However, I find the original C++ code from  Ofir Pele is  much slower than this python wrapper and I do not know why this happen.  I run the C++ code on VS 2013. Would you please help me to find the reason? Did you modify the  original C++ code? Thanks very much!

**Comment by wmayner** [comment]
I haven't modified the original code. You can see the code used by the wrapper in `pyemd/pyemd/lib` if you'd like to compare to the version you're using.

There are several possible reasons for the speed difference, depending on how you're testing and comparing things. My guess is that there are differences in the compile-time optimizations being applied by Cython and VS 2013.

**Comment by cenaliu** [comment]
@wmayner Thanks for your really quick reply! I find the reason, the speed of this fast emd algorithm not only depends on the data dimension but also depends on the data value. That's amazing! Finally, once again, thanks for your help.

**Comment by wmayner** [comment]
Yes—if you're comparing two versions of the code, you should definitely test them both with the same input.
