### ISSUE TITLE
do you have more challenging example than on main page

### ISSUE THREAD

**Issue by Sandy4321** [wmayner/pyemd#46]
do you have more challenging example than on main page
to how it works for complicated cases?
>>> from pyemd import emd
>>> import numpy as np
>>> first_histogram = np.array([0.0, 1.0])
>>> second_histogram = np.array([5.0, 3.0])
>>> distance_matrix = np.array([[0.0, 0.5],
...                             [0.5, 0.0]])
>>> emd(first_histogram, second_histogram, distance_matrix)
3.5

**Comment by wmayner** [comment]
What do you mean by more challenging? There aren't really any more "complicated" cases; you pass the two arrays and a distance matrix that defines the ground distance between their elements. You can also check the [API](https://github.com/wmayner/pyemd#emd) to understand how to use the function.

**Comment by Sandy4321** [comment]
I mean more complicated data

**Comment by wmayner** [comment]
Can you clarify why you think that would be helpful? What do you not understand about the function? I don't think using larger input would make its usage more clear, but I'm open to the idea.

**Comment by Sandy4321** [comment]
can you give example not for array of length equal to 2 but longer arrays 
by the way what is distance_matrix  in your example
can you hare link to read theory behind this distance_matrix  use
how different distance_matrix  use from not use
like
example 1
>>> from pyemd import emd_samples
>>> first_array = [1, 2, 3, 4]
>>> second_array = [2, 3, 4, 5]
>>> emd_samples(first_array, second_array, bins=2)
0.5
example 2
>>> from pyemd import emd
>>> import numpy as np
>>> first_histogram = np.array([0.0, 1.0])
>>> second_histogram = np.array([5.0, 3.0])
>>> distance_matrix = np.array([[0.0, 0.5],
...                             [0.5, 0.0]])
>>> emd(first_histogram, second_histogram, distance_matrix)

**Comment by wmayner** [comment]
Please read the documentation that I linked to in my first response. The `distance_matrix` argument is described there.

I would also recommend reading the Wikipedia page on the Earth Mover's Distance to understand what the "ground distance" is (this is what `distance_matrix` represents). That article is linked in the first paragraph of the README.
