### ISSUE TITLE
Addition of New feature: Statistical Significance test of Residue or trend component

### ISSUE THREAD

**Issue by oshin94** [wmayner/pyemd#56]
@wmayner I would like to contribute to this project by adding the test for statistical information content of EMD components.
The test allows one to identify statistically significant IMFs in a noisy data.

The methodology was proposed by Zhaohua Wu, & Huang, N. E. (2004) in their paper, "A study of the characteristics of white noise using the empirical mode decomposition method" and has been established as a method to analyse trends especially for hydrological time series.
link: [Original paper](https://www.jstor.org/stable/4143111)

Initially, only the residue component can be added, later on all IMFs can be added.

Kindly, let me know if the idea is in line with the aim of this project and if I may raise a PR.

**Comment by wmayner** [comment]
It sounds like this would be an operation performed after the EMD itself is computed. Is that right?

**Comment by oshin94** [comment]
yes, however for the test, the signal has to be normalized before the decomposition.

**Comment by oshin94** [comment]
I just noticed that I am talking about a different type of EMD: Empirical Mode Decomposition and not Earth Mover's Distance Metric. Sorry for the confusion. Closing this issue.
