### ISSUE TITLE
switch from setup.py to pyproject.toml

### ISSUE THREAD

**Issue by pabs3** [wmayner/pyemd#62]
It would be nice to switch to modern Python packaging standards at some point.

The Python community has standardised on pyproject.toml for Python packaging:

https://packaging.python.org/en/latest/tutorials/packaging-projects/

I haven't had time to complete this migration but I made a start here:

https://github.com/pabs3/pyemd/compare/cleanups...pabs3:pyemd:pyproject

**Comment by wmayner** [comment]
I agree this would be much better—thanks for getting it started.

**Comment by pabs3** [comment]
I note that setup.py uses distutils, which will be removed from Python 3.12, switching to pyproject will fix this too.

**Comment by wmayner** [comment]
Latest release uses modern packaging 🎉
