### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by pabs3** [wmayner/pyemd#63]
This is a reminder for issuing a new upstream release,
with a git tag and PyPI upload.

This will close at least the issue about Python 3.11 becase
it seems to just need running Cython to fix it.
The Debian package definitely builds fine with Python 3.11,
presumably because it runs Cython during the build process.

https://github.com/wmayner/pyemd/issues/59

In addition it will fix the test failure with recent numpy.

PS: I've uploaded a snapshot of git master to Debian.

**Comment by wmayner** [comment]
Finally had some time to finish this up. Just released version 1.0.0.
