### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by skillachie** [wmayner/pyemd#8]
I currently get a segmentation fault when i try to use pyemd.  Can you give any hints as to what might produce this from Python ?

Took a look at  https://github.com/wmayner/pyemd/blob/develop/pyemd/lib/emd_hat_impl.hpp  but not sure why it produces the Segmentation fault

`Program received signal SIGSEGV, Segmentation fault.
emd_hat_impl<double, (FLOW_TYPE_T)0>::operator() (this=this@entry=0x7fffffffd07f, POrig=..., QOrig=..., P=..., Q=..., C=..., 
    extra_mass_penalty=extra_mass_penalty@entry=-1, F=F@entry=0x0) at pyemd/lib/emd_hat_impl.hpp:435
435	pyemd/lib/emd_hat_impl.hpp: No such file or directory`

**Comment by wmayner** [comment]
Can you give more context? What are you passing to the `emd` function?

**Comment by skillachie** [comment]
Hi Will,

I discovered the issue. The  dimension of the first and second signature was bigger than that of the distance matrix. So it produced the  segmentation fault in the underlying C++ code.

Thanks for the reply.

**Comment by wmayner** [comment]
Yeah, I thought that might be it. In the next version I'm planning to put in some input validation since you're not the only one to get bitten by this.

**Comment by skillachie** [comment]
No problem. I had added validation locally.   I created a small pull request with updated test cases and a small validation.

Thank you for working on pyemd
